### ISSUE TITLE
Regarding full_example.c (not an issue per se)

### ISSUE THREAD

**Issue by mohamso** [tud-zih-energy/phdeem#3]
I think the example file (full_example.c) is rather strange.
I do not understand why the loop in on line 73 is required.

**Comment by Ferruck** [comment]
It's just an example how to gather data more than once in a row.

**Comment by mohamso** [comment]
Is it? The incrementor i is never used

**Comment by Ferruck** [comment]
Well, try to increase the maximum value of `i` and check the difference.

**Comment by Ferruck** [comment]
To give a more in-depth answer: `phdeem_get_global` collects the data since the last call. So every time you call it, you'll get the new data. No need to use the value of `i` here. You could also do this in a `while( true )` loop. Have a look at the `hdeem` docs as well, it's nothing specific for `phdeem`.
